version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/cli"
      - "/demo/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 50
    groups:
      eslint:
        patterns:
          - "*eslint*"
      opentelemetry:
        patterns:
          - "@opentelemetry/*"
      react:
        patterns:
          - "react*"
