name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'

exclude-labels:
  - 'release'

categories:
  - title: '⚠️ BREAKING CHANGES'
    collapse-after: 5
    labels:
      - 'breaking'
  - title: '🧰 Maintenance'
    collapse-after: 5
    labels:
      - 'maintenance'
  - title: '🐛 Bug Fixes'
    collapse-after: 5
    labels:
      - 'fix'
  - title: '🚀 Features'
    collapse-after: 5
    labels:
      - 'feat'

version-resolver:
  major:
    labels:
      - 'semver-major'
  minor:
    labels:
      - 'semver-minor'
  patch:
    labels:
      - 'semver-patch'
      - 'dependencies'
  default: patch

autolabeler:
  - label: 'maintenance'
    title:
      - '/(EMBR-[0-9]+\s+)?(build|ci|docs|style|refactor|perf|test|chore|deploy).*/'
  - label: 'fix'
    title:
      - '/(EMBR-[0-9]+\s+)?(fix|revert).*/'
  - label: 'feat'
    title:
      - '/(EMBR-[0-9]+\s+)?(feat).*/'
  - label: 'breaking'
    title:
      - '/(EMBR-[0-9]+\s+)?(breaking).*/'
  - label: 'semver-major'
    title: # SAME AS 'breaking'
      - '/(EMBR-[0-9]+\s+)?(breaking).*/'
  - label: 'semver-minor'
    title: # SAME AS 'feat'
      - '/(EMBR-[0-9]+\s+)?(feat).*/'
  - label: 'semver-patch'
    title: # SAME AS 'fix or maintenance'
      - '/(EMBR-[0-9]+\s+)?(fix|revert|build|ci|docs|style|refactor|perf|test|chore).*/'

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
