name: Draft Release

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  next-release:
    permissions:
      contents: write
      # write permission is required for autolabeler
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: embrace-io/release-drafter@c3db6ed8d1ba035bbf9edcd5d89c1d5064d98dfb # fork from v6.1.0
        with:
          # only create a release if the last commit merged starts with "release". Coming from .github/workflows/release.yaml
          disable-releaser: ${{ startsWith(github.event.head_commit.message, 'release') }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}